{ ... }:

{
  imports = [
    # Third-party applications
    ./Amphetamine.nix
    ./Alcove.nix
    ./AltServer.nix
    ./Antigravity.nix
    ./AppCleaner.nix
    ./AppleConfigurator.nix
    ./BetterDisplay.nix
    ./BrotherPrintScan.nix
    ./Calibre.nix
    ./Claude.nix
    ./ClaudeCode.nix
    ./CoconutBattery.nix
    ./Conductor.nix
    ./Cursor.nix
    ./DeepL.nix
    ./Dia.nix
    ./Discord.nix
    ./Equinox.nix
    ./Figma.nix
    ./Finanzblick.nix
    ./Flow.nix
    ./GeForceNOW.nix
    ./Goodnotes.nix
    ./Hush.nix
    ./IINA.nix
    ./ImageOptim.nix
    ./KarabinerElements.nix
    ./KarabinerEventViewer.nix
    ./Kiro.nix
    ./MicrosoftDefenderShim.nix
    ./MicrosoftEdge.nix
    ./MicrosoftOffice.nix
    ./MicrosoftTeams.nix
    ./Moonlight.nix
    ./Mos.nix
    ./NetNewsWire.nix
    ./Notion.nix
    ./NotionCalendar.nix
    ./Obsidian.nix
    ./OneDrive.nix
    ./Pearcleaner.nix
    ./ProtonVPN.nix
    ./QBittorrent.nix
    ./Raycast.nix
    ./Rectangle.nix
    ./Reflex.nix
    ./RustDesk.nix
    ./Shazam.nix
    ./Shottr.nix
    ./Spotify.nix
    ./Tailscale.nix
    ./Telegram.nix
    ./TheUnarchiver.nix
    ./UBlockOriginLite.nix
    ./VideoConverter.nix
    ./VideoSpeedController.nix
    ./VSCode.nix
    ./Warp.nix
    ./WhatsApp.nix
    ./WindowsApp.nix

    # System apps with dedicated folder and default.nix
    ./system
  ];
}
