apps:
  pages:
    - number: 1
      items:
        - folder:  Apps
          pages:
            - number: 1
              items:
                - App Store
                - Books
                - Calculator
                - Calendar
                - Clock
                - Contacts
                - Dictionary
                - FaceTime
                - Find My
                - Freeform
                - Home
                - Mail
                - Maps
                - Messages
                - Music
                - Notes
                - Numbers
                - Pages
                - Passwords
                - Photo Booth
                - Photos
                - Podcasts
                - Preview
                - Reminders
                - Shazam
                - Siri
                - Stocks
                - System Settings
                - Tips
                - TV
                - Voice Memos
                - Weather
        - folder: System Tools
          pages:
            - number: 1
              items:
                - Activity Monitor
                - AirPort Utility
                - Audio MIDI Setup
                - Automator
                - Bluetooth File Exchange
                - ColorSync Utility
                - Console
                - Digital Color Meter
                - Disk Utility
                - Feedback Assistant
                - Font Book
                - Grapher
                - Image Capture
                - Migration Assistant
                - Mission Control
                - Print Center
                - Screen Sharing
                - Screenshot
                - Script Editor
                - Shortcuts
                - Stickies
                - System Information
                - TextEdit
                - Time Machine
                - VoiceOver Utility
        - folder: Other
          pages:
            - number: 1
              items:
                - AppCleaner
                - BetterDisplay
                - coconutBattery
                - Equinox
                - Hush
                - iPhone Mirroring
                - Mos
                - ProtonVPN
                - Pure Paste
                - QLMarkdown
                - Raycast
                - Rectangle
                - Shottr
                - TempBox
        - folder: Photo & Video
          pages:
            - number: 1
              items:
                - Figma
                - IINA
                - ImageOptim
                - Pixelmator Pro
                - QuickTime Player
        - folder: Developer
          pages:
            - number: 1
              items:
                - Cursor
                - Terminal
                - Visual Studio Code
                - Warp
        - folder: Web & Communication
          pages:
            - number: 1
              items:
                - Arc
                - Google Chrome
                - Microsoft Edge
                - NetNewsWire
                - Safari
                - Spotify
                - WhatsApp
        - folder: Games
          pages:
            - number: 1
              items:
                - Chess
                - NVIDIA GeForce NOW
                - GFN Fix
        - folder: Productivity & Documents
          pages:
            - number: 1
              items:
                - Anki
                - ChatGPT
                - DeepL
                - Flow
                - Mathpix Snipping Tool
                - Notion
                - zoom.us
        - folder: Microsoft
          pages:
            - number: 1
              items:
                - Microsoft Defender
                - Microsoft Excel
                - Microsoft OneNote
                - Microsoft Outlook
                - Microsoft PowerPoint
                - Microsoft Remote Desktop
                - Microsoft Teams
                - Microsoft Word
                - OneDrive
        - folder: Siemens AG
          pages:
            - number: 1
              items:
                - Outlook Siemens
                - Planner Siemens
                - Teams Siemens
                - Viva Engage Siemens
widgets:
  pages: []
dock_items:
  apps:
    - /Applications/Arc.app
    - /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
    - /Applications/ChatGPT.app
    - /Applications/DeepL.app
    - /System/Applications/Reminders.app
    - /System/Applications/Calendar.app
    - /System/Applications/Photos.app
    - /Applications/Cursor.app
    - /Applications/Warp.app
    - /Applications/Spotify.app
  others:
    - path: ~/Downloads
      sort: 2
  settings:
    autohide: true
    largesize: null
    magnification: false
    minimize-to-application: true
    mru-spaces: false
    show-recents: true
    tilesize: 46
desktop: {}
