apps:
  pages:
    - number: 1
      items:
        - folder:  Apps
          pages:
            - number: 1
              items:
                - App Store
                - Books
                - Calculator
                - Calendar
                - Clock
                - Contacts
                - Dictionary
                - FaceTime
                - Find My
                - Freeform
                - Home
                - Mail
                - Maps
                - Messages
                - Music
                - Notes
                - Numbers
                - Pages
                - Passwords
                - Photo Booth
                - Photos
                - Podcasts
                - Preview
                - Reminders
                - Shazam
                - Siri
                - Stocks
                - System Settings
                - Tips
                - TV
                - Voice Memos
                - Weather
        - folder: System Tools
          pages:
            - number: 1
              items:
                - Activity Monitor
                - AirPort Utility
                - Audio MIDI Setup
                - Automator
                - Bluetooth File Exchange
                - ColorSync Utility
                - Console
                - Digital Colour Meter
                - Disk Utility
                - Feedback Assistant
                - Font Book
                - Grapher
                - Image Capture
                - Migration Assistant
                - Mission Control
                - Print Centre
                - Screen Sharing
                - Screenshot
                - Script Editor
                - Shortcuts
                - Stickies
                - System Information
                - TextEdit
                - Time Machine
                - VoiceOver Utility
        - folder: Other
          pages:
            - number: 1
              items:
                - Amphetamine
                - AppCleaner
                - BetterDisplay
                - coconutBattery
                - Cork
                - DisplayLink Manager
                - Equinox
                - Hush
                - iPhone Mirroring
                - Karabiner-Elements
                - Karabiner-EventViewer
                - Keka
                - Mos
                - NotchNook
                - Pearcleaner
                - ProtonVPN
                - Pure Paste
                - QLMarkdown
                - Raycast
                - Rectangle
                - Shottr
                - TempBox
        - folder: Photo & Video
          pages:
            - number: 1
              items:
                - Figma
                - Foldor
                - Freepik
                - IINA
                - ImageOptim
                - OBS
                - Photomator
                - Pixelmator Pro
                - QuickTime Player
                - Sketch
                - Subler
                - TouchRetouch
        - folder: Developer
          pages:
            - number: 1
              items:
                - Cursor
                - Parallels Desktop
                - Parallels Desktop Activation Tool SIP ON
                - PowerShell
                - RustDesk
                - Terminal
                - Visual Studio Code
                - Warp
        - folder: Web & Communication
          pages:
            - number: 1
              items:
                - Arc
                - Discord
                - Google Chrome
                - Kleinanzeigen
                - Microsoft Edge
                - NetNewsWire
                - Safari
                - Spotify
                - WhatsApp
        - folder: Games
          pages:
            - number: 1
              items:
                - Chess
                - NVIDIA GeForce NOW
        - folder: Productivity & Documents
          pages:
            - number: 1
              items:
                - Afirstsoft PDF
                - Anki
                - ChatGPT
                - DeepL
                - Flow
                - Logseq
                - Mathpix Snipping Tool
                - Notion
                - Obsidian
                - PDF Expert
                - ProNotes
                - Typora
                - Ulysses
                - Wondershare PDFelement
                - zoom.us
        - folder: Microsoft
          pages:
            - number: 1
              items:
                - Microsoft Defender
                - Microsoft Excel
                - Microsoft OneNote
                - Microsoft Outlook
                - Microsoft PowerPoint
                - Microsoft Remote Desktop
                - Microsoft Teams
                - Microsoft Word
                - OneDrive
        - folder: Siemens AG
          pages:
            - number: 1
              items:
                - Copilot
                - Office 365 Siemens
                - Outlook Siemens
                - Planner Siemens
                - Teams Siemens
                - To Do Siemens
                - Viva Engage
widgets:
  pages: []
dock_items:
  apps:
    - /Applications/Arc.app
    - /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
    - /Applications/ChatGPT.app
    - /Applications/DeepL.app
    - /System/Applications/Reminders.app
    - /System/Applications/Calendar.app
    - /System/Applications/Photos.app
    - /Applications/Cursor.app
    - /Applications/Warp.app
    - /Applications/Spotify.app
  others:
    - path: ~/Downloads
      sort: 2
  settings:
    autohide: true
    largesize: 16
    magnification: false
    minimize-to-application: true
    mru-spaces: false
    show-recents: true
    tilesize: 52
desktop: {}
