apps:
  pages:
    - number: 1
      items:
        - folder: Utilities
          pages:
            - number: 1
              items:
                - Siri
                - Equinox
                - BetterDisplay
                - System Settings
                - Video Speed Controller
                - AppCleaner
                - Mos
                - Shottr
                - Voice Memos
                - App Store
        - folder: Productivity
          pages:
            - number: 1
              items:
                - Safari
                - Raycast
                - Rectangle
                - Notion
                - OneDrive
                - Notes
                - Freeform
                - Preview
                - Microsoft Word
                - TextEdit
                - 1Blocker
                - Arc
                - Microsoft Excel
                - ChatGPT
                - Mail
                - Microsoft Outlook
                - Contacts
                - Flow
                - Microsoft OneNote
                - Microsoft PowerPoint
                - ColorSync Utility
                - Digital Color Meter
                - Stickies
                - Reminders
                - Calendar
        - folder: Developer Tools
          pages:
            - number: 1
              items:
                - Visual Studio Code
                - Warp
                - Cursor
        - folder: Music
          pages:
            - number: 1
              items:
                - Music
                - Spotify
        - folder: Graphics Design
          pages:
            - number: 1
              items:
                - Figma
        - folder: Reference
          pages:
            - number: 1
              items:
                - DeepL
                - Dictionary
        - folder: Video
          pages:
            - number: 1
              items:
                - QuickTime Player
                - IINA
                - TV
        - folder: Board Games
          pages:
            - number: 1
              items:
                - Chess
        - folder: Entertainment
          pages:
            - number: 1
              items:
                - Photo Booth
        - folder: Books
          pages:
            - number: 1
              items:
                - Books
        - folder: Business
          pages:
            - number: 1
              items:
                - Windows App
        - folder: News
          pages:
            - number: 1
              items:
                - NetNewsWire
        - folder: Social Networking
          pages:
            - number: 1
              items:
                - WhatsApp
                - FaceTime
                - Messages
        - folder: Games
          pages:
            - number: 1
              items:
                - NVIDIA GeForce NOW
        - folder: Education
          pages:
            - number: 1
              items:
                - Grapher
                - Tips
        - folder: Travel
          pages:
            - number: 1
              items:
                - Maps
        - folder: Photography
          pages:
            - number: 1
              items:
                - Photos
        - folder: Misc
          pages:
            - number: 1
              items:
                - Find My
                - Microsoft Defender
                - Karabiner-Elements
                - Karabiner-EventViewer
                - Weather
                - Home
                - coconutBattery
                - Passwords
                - Podcasts
                - Stocks
                - Microsoft Edge
                - Microsoft Teams
                - Disk Utility
                - iPhone Mirroring
                - Calculator
                - Clock
        - folder: Other
          pages:
            - number: 1
              items:
                - Shortcuts
                - Font Book
                - Screen Sharing
                - Mission Control
                - Time Machine
                - Screenshot
                - Image Capture
                - VoiceOver Utility
                - Print Center
                - Automator
                - Script Editor
                - Audio MIDI Setup
                - Bluetooth File Exchange
                - System Information
                - Activity Monitor
                - Console
                - Terminal
                - AirPort Utility
                - Migration Assistant
widgets:
  pages: []
dock_items:
  apps:
    - /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
    - /Applications/WhatsApp.app
    - /System/Applications/Photos.app
    - /System/Applications/Calendar.app
    - /System/Applications/Reminders.app
    - /System/Applications/Notes.app
    - /Applications/Microsoft OneNote.app
    - /System/Applications/Passwords.app
    - /System/Applications/System Settings.app
    - /Applications/Warp.app
  others:
    - path: ~/Downloads
      view: 1
      sort: 2
  settings:
    autohide: true
    largesize: null
    magnification: false
    minimize-to-application: false
    mru-spaces: false
    show-recents: false
    tilesize: 53
desktop: {}
